# --- Knative Service ---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: anselmschaefer/petison:1.5.0
          ports:
            - containerPort: 8080

---
# --- Direct Kubernetes Service for Port-Forwarding ---
# This will always route traffic to all pods in the latest revision
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-direct
  namespace: default
spec:
  selector:
    serving.knative.dev/service: spring-boot-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080