apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: anselmschaefer/petison:1.8.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30       # increase if app starts slowly
            periodSeconds: 5
            failureThreshold: 6