apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

    volumes:
      - name: acme-storage
        emptyDir: {}

    volumeMounts:
      - name: acme-storage
        mountPath: /data
    
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"

    # Add middleware for redirecting HTTP to HTTPS
    middleware:
      redirect-to-https:
        redirectScheme:
          scheme: https
          permanent: true

    # Tell the web entrypoint to use the middleware
    entryPoints:
      web:
        address: ":80"
        http:
          middlewares:
            - redirect-to-https@kubernetescrd